name: MMCCore
version: '${project.version}'
main: mandomc.mmccore.MMCCore
api-version: 1.19
load: STARTUP
authors: [ AstuteFlamez ]
description: A core plugin for the minecraft server MandoMC.
depend: [MythicMobs]
commands:
  yaw:
  pitch:
  startkoth: